images:
  # This is pinned to a specific AMI
  aptos-ubuntu-x64:
    platform: "linux"
    arch: "x64"
    ami: "ami-05f29bbd9fcfcca20"
  
  # Points to the latest image prefixed with aptos-. Use this for testing manually built images
  aptos-ubuntu-x64-latest:
    platform: "linux"
    arch: "x64"
    owner: "058264343338" # aptos-ci AWS account id
    name: "aptos-runs-on-*"

  # Points to the latest image built by the build-runs-on-image workflow
  aptos-ubuntu-x64-stable:
    platform: "linux"
    arch: "x64"
    owner: "058264343338" # aptos-ci AWS account id
    name: "aptos-stable-runs-on-*"
